### ISSUE TITLE
Ability to group CSS Variables under multiple selectors

### ISSUE THREAD

**Issue by nareshbhatia** [tokens-studio/sd-transforms#227]
### What feature would you like?

I would like to generate CSS Variables so that they are grouped under 3 selectors:

```css
:root {
  --color-black: #000000;
  --color-white: #ffffff;
  ...
}

.theme-light {
  --color-bg-default: #ffffff;
  ...
}

.theme-dark {
  --color-bg-default: #000000;
  ...
}
```

However a configuration like the one below, puts everything under `:root`:

```js
const config = {
  source: [
    'global/global.json',
    'mode/light.json',
    'mode/dark.json',
  ],
  platforms: {
    css: {
      transformGroup: 'tokens-studio',
      buildPath: '../output/',
      files: [
        {
          destination: `vars.css`,
          format: 'css/variables',
        },
      ],
    },
  },
};
```

I know that `file` has a option called `selector`, but is it possible to apply it selectively to source files?

### Would you be available to contribute this feature?

- [ ] Yes, I would like to contribute this
