### ISSUE TITLE
Referencing is broken when parent key is included in JSON

### ISSUE THREAD

**Issue by ajkl2533** [tokens-studio/sd-transforms#31]
Hi guys, excellent work with this library.

I find out that if Tokens Studio exports tokens into JSON file there is an option to include the parent key. But when you leave that checkbox checked (by default) it breaks the referencing to other tokens. Basically `style.dictionary` is trying to reference `space.1x` but the json path is in fact `global.space.1x`.  

It wouldn't be such an issue for manual exports but there is no way how to control this checkbox when using sync with a provider (e.g. Github) and in that case, the parent key is always included.

<img width="523" alt="Screenshot 2023-02-23 at 12 05 35" src="https://user-images.githubusercontent.com/18654425/220890776-9f28f698-a0f4-4b21-b678-eebbc7229437.png">
<img width="523" alt="Screenshot 2023-02-23 at 12 08 14" src="https://user-images.githubusercontent.com/18654425/220890781-c2b5526f-796e-4415-ae6b-90332415b643.png">

**Comment by jorenbroekema** [comment]
@six7 I think the best solution would be to allow Sync providers in the plugin to sync without parent keys.

As a workaround, use https://www.npmjs.com/package/token-transformer , which gives you a style-dictionary compatible output when you give Figma Tokens JSON as input.

You could run this token-transformer automatically with GitHub Actions, whenever the plugin sync feature syncs to your branch:
```yaml
name: Get rid of parent keys tokens

# match the branch you put in your Tokens Studio for Figma sync credentials
on:
  push:
    branches:
      - figma-tokens

jobs:
  name: Get rid of parent keys tokens
  runs-on: ubuntu-latest
  timeout-minutes: 5
  steps:
    - uses: actions/checkout@2
    
    - name: Install Dependencies
      run: npm install

    - name: Run token-transformer script
      run: npx token-transformer figma-tokens-output.json sd-input.json --resolveReferences false

    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      with:
        author_name: Example
        author_email: example@gmail.com
        message: 'chore: style-dictionary output'
        add: '.'
```
Make sure to adjust ^^^^ variables to match your own author/settings.

It assumes your tokens are synced by the plugin into Github repo on `figma-tokens-output.json` and that style-dictionary will look for `sd-input.json`.
