### ISSUE TITLE
[Feature]: CSS light-dark() output?

### ISSUE THREAD

**Issue by brian-patrick-3** [tokens-studio/sd-transforms#324]
### What feature would you like?

Having a light and a dark theme, is it possible to generate variables using the CSS `light-dark()` syntax?

Ex desired output:
```css
:root {
  /* palette tokens */
  --kd-color-black: #000;
  --kd-color-white: #fff;
    
  /* named tokens */
  --kd-color-text: light-dark(var(--kd-color-black), var(--kd-color-white));
  --kd-color-background: light-dark(var(--kd-color-white), var(--kd-color-black));
}
```

If yes, how would we need to structure the tokens in tokens studio to get the right JSON output?

### Would you be available to contribute this feature?

- [ ] Yes, I would like to contribute this
